# Make sure there's a trailing slash!
baseURL: https://bxt.rs/
languageCode: en-us
title: Ivan Molodetskikh’s Webpage
theme: mini

permalinks:
  posts: /blog/:title/

markup:
  highlight:
    style: pygments
    noClasses: false

taxonomies:
  tag: tags

params:
  author: Ivan Molodetskikh
  subscribe: RSS
  enableRSS: true

  env: production
  enableComments: false

  social:
    - name: email
      url: mailto:yalterz@gmail.com
    - name: mastodon
      url: https://mastodon.online/@YaLTeR
    - name: twitter
      url: https://twitter.com/YaLTeRz
    - name: github
      url: https://github.com/YaLTeR
    - name: gitlab
      url: https://gitlab.gnome.org/YaLTeR
