name = "mini"
license = "MIT"
licenselink = "https://github.com/nodejh/hugo-theme-mini/blob/master/LICENSE.md"
description = "A fast, minimalist and responsive hugo theme for bloggers."
homepage = "https://github.com/nodejh/hugo-theme-mini"
tags = ["blog", "fast", "minimalist", "responsive", "simple", "beautiful", "tags", "pages"]
features = ["fast", "minimalist", "responsive", "archive", "tags"]
min_version = "0.75.0"

[author]
    name = "nodejh"
    homepage = "https://github.com/nodejh"